# Copyright 2021 Google LLC
# Copyright 2023 Andrew Pritchard
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: keyed-containers
version: 0.1.0
category: Data Structures
synopsis: Container wrappers with typed-key APIs
description: |
  Wraps @IntMap@ and @IntSet@ in APIs that allow using newtypes over @Int@ for
  their keys/indices.  (This is everything from @containers@ that's suitable
  for this transformation).

  Admittedly it's a bit weird to call this a "keyed" @IntSet@.  I haven't been
  able to come up with a name that isn't worse.
license: Apache-2.0
author: Andrew Pritchard <awpritchard@gmail.com>
copyright: 2021 Google LLC; 2023 Andrew Pritchard
maintainer: Andrew Pritchard <awpritchard@gmail.com>
github: awpr/niche-containers/keyed-containers

# Note: this causes CHANGELOG.md to be included in Hackage distributions.
extra-source-files:
  - CHANGELOG.md
  - src/Data/IntMap/Keyed/Impl.hs.inc

dependencies:
  - base >= 4.12 && < 4.19
  - attenuation >= 0.2 && < 0.3
  - containers >= 0.6 && < 0.7
  - deepseq >= 1.4 && < 1.5
  - indexed-traversable >= 0.1 && < 0.2
  - portray >= 0.1 && < 0.4
  - portray-diff >= 0.1 && < 0.2
  - wrapped >= 0.1 && < 0.2

library:
  source-dirs: src
  exposed-modules:
    - Data.IntMap.Keyed
    - Data.IntMap.Keyed.Lazy
    - Data.IntMap.Keyed.Strict
    - Data.IntSet.Keyed
  other-modules:
    - Data.IntSet.Keyed.Internal

  when:
    condition: false
    other-modules: Paths_keyed_containers
